name: Docker Image CI
on: [push]

jobs:
  build:
    uses: chrisns/repo-config/.github/workflows/dockerbuild.yml@main
    with:
      platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
