name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/setup-qemu-action@v1.1.0

      - name: Login to dockerhub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Prepare
        id: prepare
        run: |
          TAGS=${GITHUB_REPOSITORY}:sha-${GITHUB_SHA},ghcr.io/${GITHUB_REPOSITORY}:sha-${GITHUB_SHA}
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            TAGS=$TAGS,${GITHUB_REPOSITORY}:latest,ghcr.io/${GITHUB_REPOSITORY}:latest
          fi
          echo ::set-output name=TAGS::${TAGS}

      - name: build+push
        uses: docker/build-push-action@v2.4.0
        with:
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.prepare.outputs.TAGS }}
